INSERT INTO Universities (uni_name, uni_type, uni_website) VALUES ('University of Dhaka', 'Public',  'www.du.ac.bd');
INSERT INTO Universities (uni_name, uni_type, uni_website) VALUES ('University of Rajshahi', 'Public',  'www.ru.ac.bd');
INSERT INTO Universities (uni_name, uni_type, uni_website) VALUES ('Bangladesh Agricultural University', 'Public',  'www.bau.edu.bd');
INSERT INTO Universities (uni_name, uni_type, uni_website) VALUES ('Bangladesh University of Engineering & Technology', 'Public',  'www.buet.ac.bd');
INSERT INTO Universities (uni_name, uni_type, uni_website) VALUES ('University of Chittagong', 'Public',  'www.cu.ac.bd');
INSERT INTO Universities (uni_name, uni_type, uni_website) VALUES ('Jahangirnagar University', 'Public',  'www.juniv.edu');
INSERT INTO Universities (uni_name, uni_type, uni_website) VALUES ('Islamic University, Bangladesh', 'Public',  'www.iu.ac.bd');
INSERT INTO Universities (uni_name, uni_type, uni_website) VALUES ('Shahjalal University of Science & Technology', 'Public',  'www.sust.edu');
INSERT INTO Universities (uni_name, uni_type, uni_website) VALUES ('Khulna University', 'Public',  'www.ku.ac.bd');
INSERT INTO Universities (uni_name, uni_type, uni_website) VALUES ('National University', 'Public',  'www.nu.edu.bd');
INSERT INTO Universities (uni_name, uni_type, uni_website) VALUES ('Bangladesh Open University', 'Public',  'www.bou.ac.bd');
INSERT INTO Universities (uni_name, uni_type, uni_website) VALUES ('Bangabandhu Sheikh Mujib Medical University', 'Public',  'www.bsmmu.edu.bd');
INSERT INTO Universities (uni_name, uni_type, uni_website) VALUES ('Bangabandhu Sheikh Mujibur Rahman Agricultural University', 'Public',  'www.bsmrau.edu.bd');
INSERT INTO Universities (uni_name, uni_type, uni_website) VALUES ('Hajee Mohammad Danesh Science & Technology University', 'Public',  'www.hstu.ac.bd');
INSERT INTO Universities (uni_name, uni_type, uni_website) VALUES ('Mawlana Bhashani Science & Technology University', 'Public',  'www.mbstu.ac.bd');
INSERT INTO Universities (uni_name, uni_type, uni_website) VALUES ('Patuakhali Science And Technology University', 'Public',  'www.pstu.ac.bd');
INSERT INTO Universities (uni_name, uni_type, uni_website) VALUES ('Sher-e-Bangla Agricultural University', 'Public',  'www.sau.edu.bd');
INSERT INTO Universities (uni_name, uni_type, uni_website) VALUES ('Chittagong University of Engineering & Technology', 'Public',  'www.cuet.ac.bd');
INSERT INTO Universities (uni_name, uni_type, uni_website) VALUES ('Rajshahi University of Engineering & Technology', 'Public',  'www.ruet.ac.bd');
INSERT INTO Universities (uni_name, uni_type, uni_website) VALUES ('Khulna University of Engineering & Technology', 'Public',  'www.kuet.ac.bd');
INSERT INTO Universities (uni_name, uni_type, uni_website) VALUES ('Dhaka University of Engineering & Technology', 'Public',  'www.duet.ac.bd');
INSERT INTO Universities (uni_name, uni_type, uni_website) VALUES ('Noakhali Science & Technology University', 'Public',  'www.nstu.edu.bd');
INSERT INTO Universities (uni_name, uni_type, uni_website) VALUES ('Jagannath University', 'Public',  'www.jnu.ac.bd');
INSERT INTO Universities (uni_name, uni_type, uni_website) VALUES ('Comilla University', 'Public',  'www.cou.ac.bd');
INSERT INTO Universities (uni_name, uni_type, uni_website) VALUES ('Jatiya Kabi Kazi Nazrul Islam University', 'Public',  'www.jkkniu.edu.bd');
INSERT INTO Universities (uni_name, uni_type, uni_website) VALUES ('Chittagong Veterinary and Animal Sciences University', 'Public',  'www.cvasu.ac.bd');
INSERT INTO Universities (uni_name, uni_type, uni_website) VALUES ('Sylhet Agricultural University', 'Public',  'www.sau.ac.bd');
INSERT INTO Universities (uni_name, uni_type, uni_website) VALUES ('Jessore University of Science & Technology', 'Public',  'www.just.edu.bd');
INSERT INTO Universities (uni_name, uni_type, uni_website) VALUES ('Pabna University of Science and Technology', 'Public',  'www.pust.ac.bd');
INSERT INTO Universities (uni_name, uni_type, uni_website) VALUES ('Begum Rokeya University, Rangpur', 'Public',  'www.brur.ac.bd');
INSERT INTO Universities (uni_name, uni_type, uni_website) VALUES ('Bangladesh University of Professionals', 'Public',  'www.bup.edu.bd');
INSERT INTO Universities (uni_name, uni_type, uni_website) VALUES ('Bangabandhu Sheikh Mujibur Rahman Science & Technology University', 'Public',  'www.bsmrstu.edu.bd');
INSERT INTO Universities (uni_name, uni_type, uni_website) VALUES ('Bangladesh University of Textiles', 'Public',  'www.butex.edu.bd');
INSERT INTO Universities (uni_name, uni_type, uni_website) VALUES ('University of Barishal', 'Public',  'www.bu.ac.bd');
INSERT INTO Universities (uni_name, uni_type, uni_website) VALUES ('Rangamati Science and Technology University', 'Public',  'www.rmstu.edu.bd');
INSERT INTO Universities (uni_name, uni_type, uni_website) VALUES ('Bangabandhu Sheikh Mujibur Rahman Maritime University, Bangladesh', 'Public',  'www.bsmrmu.edu.bd');
INSERT INTO Universities (uni_name, uni_type, uni_website) VALUES ('Islamic Arabic University', 'Public',  'www.iau.edu.bd');
INSERT INTO Universities (uni_name, uni_type, uni_website) VALUES ('Chittagong Medical University', 'Public',  'www.cmu.edu.bd');
INSERT INTO Universities (uni_name, uni_type, uni_website) VALUES ('Rajshahi Medical University', 'Public',  'www.rmu.edu.bd');
INSERT INTO Universities (uni_name, uni_type, uni_website) VALUES ('Rabindra University, Bangladesh', 'Public',  'www.rub.ac.bd');
INSERT INTO Universities (uni_name, uni_type, uni_website) VALUES ('Bangabandhu Sheikh Mujibur Rahman Digital University, Bangladesh', 'Public',  'www.bdu.ac.bd');
INSERT INTO Universities (uni_name, uni_type, uni_website) VALUES ('Sheikh Hasina University', 'Public',  'https://shubd.net/');
INSERT INTO Universities (uni_name, uni_type, uni_website) VALUES ('Khulna Agricultural University', 'Public',  'www.kau.edu.bd');
INSERT INTO Universities (uni_name, uni_type, uni_website) VALUES ('Bangamata Sheikh Fojilatunnesa Mujib Science and Technology University', 'Public',  'https://bsfmstu.ac.bd/');
INSERT INTO Universities (uni_name, uni_type, uni_website) VALUES ('Sylhet Medical University', 'Public',  'www.smu.edu.bd');
INSERT INTO Universities (uni_name, uni_type, uni_website) VALUES ('Bangabandhu Sheikh Mujibur Rahman Aviation And Aerospace University (BSMRAAU)', 'Public',  'www.bsmraau.edu.bd');
INSERT INTO Universities (uni_name, uni_type, uni_website) VALUES ('Chandpur Science and Technology University', 'Public',  '.');
INSERT INTO Universities (uni_name, uni_type, uni_website) VALUES ('Bangabandhu Sheikh Mujibur Rahman University, Kishoreganj', 'Public',  'bsmru.ac.bd.');
INSERT INTO Universities (uni_name, uni_type, uni_website) VALUES ('Hobiganj Agricultural University', 'Public',  'www.hau.ac.bd');
INSERT INTO Universities (uni_name, uni_type, uni_website) VALUES ('Sheikh Hasina Medical University, Khulna', 'Public',  '');
INSERT INTO Universities (uni_name, uni_type, uni_website) VALUES ('Kurigram Agricultural University', 'Public',  '.');
INSERT INTO Universities (uni_name, uni_type, uni_website) VALUES ('Sunamganj Science and Technology University', 'Public',  '.');
INSERT INTO Universities (uni_name, uni_type, uni_website) VALUES ('Bangabandhu Sheikh Mujibur Rahman Science & Technology University, Pirojpur', 'Public',  '.');

